/**
 * @file store.js
 * @description Central shared application state and cached DOM element references.
 */

export const state = {
  sessionToken: '',
  userEmail: '',
  feeds: [],
  mutedFeeds: [],
  feedMetadata: {},
  allEpisodes: [],
  filteredEpisodes: [],
  playbackPositions: {},
  currentEpisode: null,
  playbackSpeed: 1.0,
  sortOrder: 'newest',
  searchQuery: '',
  filterMode: 'unplayed',
  feedFilter: 'all',
  ytPlayer: null,
  ytReady: false,
  activeEngine: 'audio',
  playbackStatus: 'idle',
  timelinePage: 1,
  pageSize: 30,
  activeFeedDetailUrl: null,
  navHistory: [],          // stack of { tab, feedUrl } entries for back navigation
  continueCollapsed: true,
  queue: [],
  favorites: [],
  favoriteGuids: new Set(),
  downloadedEpisodes: {},
  downloadingGuids: new Set(),
  directoryCountry: 'all',
  sleepTimer: {
    active: false,
    minutes: 0,
    endTime: null,
    intervalId: null,
    fadeout: true,
    initialVolume: 1.0
  },
  experimentalSettings: {
    enableVisualizer: true,
    enableAudioClassifier: false,
    autoSkipSpeech: false,
    enableTranscript: false,
    enableVolumeBoost: false,
    enableSilenceSkip: false
  },
  episodeTimeline: {
    guid: null,
    duration: 0,
    bars: [],        // array of { height: 0..1, type: 'speech' | 'music' | 'neutral', time: seconds }
    segments: [],    // array of { start: s, end: s, type: 'speech' | 'music' }
    cues: [],        // array of { start: s, end: s, text: string, type: 'speech' }
    transcriptSource: '',
    isProbing: false,
    progressPct: 0
  },
  showRemainingTime: true,
  isTabActive: typeof document !== 'undefined' ? !document.hidden : true,
  _activeCardCache: null,
  _lastDrawnWaveformBarIndex: -1
};

// Visibility change listener to keep state.isTabActive updated
document.addEventListener('visibilitychange', () => {
  state.isTabActive = !document.hidden;
});

export const elements = {};

/**
 * Initializes and caches all DOM node references.
 */
export function initElementsCache() {
  if (typeof document === 'undefined') return;

  const get = (id) => document.getElementById(id);
  const query = (sel) => document.querySelector(sel);
  const queryAll = (sel) => document.querySelectorAll(sel);

  Object.assign(elements, {
    authModal: get('auth-modal'),
    btnCloseAuth: get('btn-close-auth'),
    btnCancelAuth: get('btn-cancel-auth'),
    magicAuthForm: get('magic-auth-form'),
    magicEmailInput: get('magic-email-input'),
    btnSubmitMagic: get('btn-submit-magic'),
    magicStatusMsg: get('magic-status-msg'),
    userSyncStatus: get('user-sync-status'),
    btnShowLogin: get('btn-show-login'),
    userStatusPill: get('user-status-pill'),
    statusIndicator: get('status-indicator'),
    userEmailLabel: get('user-email-label'),
    btnAccountToggle: get('btn-account-toggle'),

    confirmModal: get('confirm-modal'),
    confirmModalMsg: get('confirm-modal-msg'),
    btnConfirmCancel: get('btn-confirm-cancel'),
    btnConfirmDelete: get('btn-confirm-delete'),
    btnPrev15: get('btn-prev-15'),
    btnNext15: get('btn-next-15'),
    btnSkipEpisode: get('btn-skip-episode'),
    btnPlayerMarkPlayed: get('btn-player-mark-played'),

    tabs: queryAll('.nav-tab'),
    panels: queryAll('.tab-panel'),
    tabFeeds: get('tab-feeds'),
    tabTimeline: get('tab-timeline'),
    tabFavorites: get('tab-favorites'),
    tabDownloads: get('tab-downloads'),
    tabSettings: get('tab-settings'),
    panelFeeds: get('panel-feeds'),
    panelTimeline: get('panel-timeline'),
    panelFavorites: get('panel-favorites'),
    panelDownloads: get('panel-downloads'),
    panelFeedDetail: get('panel-feed-detail'),
    feedDetailHeader: get('feed-detail-header'),
    feedDetailEpisodes: get('feed-detail-episodes'),
    favoritesEpisodesList: get('favorites-episodes-list'),
    favoritesHeaderCount: get('favorites-header-count'),
    themeBtns: queryAll('.btn-theme'),
    feedCount: get('feed-count'),
    favoritesTabCount: get('favorites-tab-count'),
    downloadsTabCount: get('downloads-tab-count'),
    btnOpenSettings: get('btn-open-settings'),
    btnPlayerFav: get('btn-player-fav'),

    omnibar: get('omnibar'),
    searchInput: get('omnibar') || get('search-input'),
    searchBarWrap: get('search-bar-wrap'),
    btnClearSearch: get('btn-clear-search'),
    sortOrderSelect: get('sort-order'),
    btnOpenAddModal: get('btn-open-add-modal'),
    btnRefreshAll: get('btn-refresh-all'),
    statusBanner: get('status-banner'),

    timelineList: get('timeline-list'),
    feedsFilterBar: get('feeds-filter-bar'),
    feedsFilterChips: get('feeds-filter-chips'),
    feedsGrid: get('feeds-grid'),
    continueShelf: get('continue-shelf'),
    continueGrid: get('continue-grid'),
    continueCount: get('continue-count'),
    btnToggleContinue: get('btn-toggle-continue'),
    continueToggleLabel: get('continue-toggle-label'),
    continueStickyBar: get('continue-sticky-bar'),
    btnContinueStickyCollapse: get('btn-continue-sticky-collapse'),
    playedCount: get('played-count'),
    downloadedCount: get('downloaded-count'),
    offlineBadge: get('offline-badge'),
    offlineStorageCard: get('offline-storage-card'),
    offlineStorageCount: get('offline-storage-count'),
    btnClearDownloads: get('btn-clear-downloads'),
    offlineEpisodesList: get('offline-episodes-list'),
    filterChips: queryAll('.chip-filter'),
    bottomActionDock: get('bottom-action-dock'),

    opmlFileInput: get('opml-file-input'),
    btnExportOpml: get('btn-export-opml'),
    btnLoadDefaults: get('btn-load-defaults'),
    btnReloadCache: get('btn-reload-cache'),
    btnClearStorage: get('btn-clear-storage'),

    addModal: get('add-modal'),
    addModalNav: get('add-modal-nav'),
    addModalBody: get('add-modal-body'),
    btnToggleEnlarge: get('btn-toggle-enlarge'),
    dirResultsTitle: get('dir-results-title'),
    dirStickyCollapseBar: get('dir-sticky-collapse-bar'),
    btnStickyCollapse: get('btn-sticky-collapse'),
    podcastSearchQuery: get('podcast-search-query'),
    btnClearModalSearch: get('btn-clear-modal-search'),
    btnSearchDirectory: get('btn-search-directory'),
    searchDirectoryResults: get('search-directory-results'),
    modalSubgenreChips: get('modal-subgenre-chips'),
    feedUrlInput: get('feed-url-input'),
    btnCloseAdd: get('btn-close-add'),
    btnCancelAdd: get('btn-cancel-add'),
    btnSubmitFeed: get('btn-submit-feed'),

    sleepModal: get('sleep-modal'),
    btnCloseSleep: get('btn-close-sleep'),
    btnOpenSleep: get('btn-open-sleep'),
    sleepBadge: get('sleep-badge'),
    timerBtns: queryAll('.timer-btn'),
    fadeoutCheck: get('fadeout-check'),

    btnOpenQueue: get('btn-open-queue'),
    btnCloseQueue: get('btn-close-queue'),
    btnClearQueue: get('btn-clear-queue'),
    queueModal: get('queue-modal'),
    queueBadge: get('queue-badge'),
    queueCountBadge: get('queue-count-badge'),
    queueNowPlayingContainer: get('queue-now-playing-container'),
    queueItemsContainer: get('queue-items-container'),

    showNotesModal: get('show-notes-modal'),
    btnCloseNotes: get('btn-close-notes'),
    showNotesPodcastTitle: get('show-notes-podcast-title'),
    showNotesEpisodeTitle: get('show-notes-episode-title'),
    showNotesMeta: get('show-notes-meta'),
    showNotesContent: get('show-notes-content'),
    tabBtnNotes: get('tab-btn-notes'),
    tabBtnTranscript: get('tab-btn-transcript'),
    transcriptSourcePill: get('transcript-source-pill'),
    showTranscriptContent: get('show-transcript-content'),
    transcriptSearchInput: get('transcript-search-input'),
    transcriptFileInput: get('transcript-file-input'),
    transcriptCuesList: get('transcript-cues-list'),

    audio: get('audio-engine'),
    playerBar: get('player-bar'),
    playerTrackInfo: query('.player-track-info'),
    playerArtwork: get('player-artwork'),
    playerTitle: get('player-title'),
    playerPodcast: get('player-podcast'),
    btnPlayToggle: get('btn-play-toggle'),
    iconPlay: query('.icon-play'),
    iconPause: query('.icon-pause'),
    iconSpinner: query('.icon-spinner'),
    currentTimeLabel: get('current-time'),
    totalDurationLabel: get('total-duration'),
    seekBar: get('seek-bar'),
    btnSpeedToggle: get('btn-speed-toggle'),
    btnPlayerTranscript: get('btn-player-transcript'),
    btnPlayerNotes: get('btn-player-notes'),
    btnPlayerShare: get('btn-player-share'),
    playerStatusBadges: get('player-status-badges'),
    btnCollapsePlayer: get('btn-collapse-player'),
    playerMini: get('player-mini'),
    miniExpandZone: get('mini-expand-zone'),
    miniArtwork: get('mini-artwork'),
    miniTitle: get('mini-title'),
    miniPodcast: get('mini-podcast'),
    miniPlayToggle: get('mini-play-toggle'),
    miniIconPlay: query('.mini-icon-play'),
    miniIconPause: query('.mini-icon-pause'),
    miniIconSpinner: query('.mini-icon-spinner'),
    miniOpenQueue: get('mini-open-queue'),
    miniQueueDot: get('mini-queue-dot'),
    miniStatusBadges: get('mini-status-badges'),
    miniToggle: get('mini-toggle'),
    miniProgressFill: get('mini-progress-fill'),

    timeScrubber: get('time-scrubber'),
    timelineLegend: get('timeline-legend'),
    waveformTimelineWrap: get('waveform-timeline-wrap'),
    episodeWaveformCanvas: get('episode-waveform-canvas'),
    waveformProgressOverlay: get('waveform-progress-overlay'),
    waveformPlayheadLine: get('waveform-playhead-line'),
    waveformHoverCursor: get('waveform-hover-cursor'),
    waveformTooltip: get('waveform-tooltip'),
    btnJumpSpeech: get('btn-jump-speech'),
    btnJumpMusic: get('btn-jump-music'),
    probeStatusPill: get('probe-status-pill'),

    toggleVisualizer: get('toggle-visualizer'),
    toggleClassifier: get('toggle-classifier'),
    toggleAutoSkip: get('toggle-auto-skip'),
    toggleVolumeBoost: get('toggle-volume-boost'),
    toggleSilenceSkip: get('toggle-silence-skip'),
    toggleTranscript: get('toggle-transcript'),
    experimentalStatus: get('experimental-status'),

    btnHeaderBack: get('btn-header-back'),
    btnHeaderBackLabel: get('btn-header-back-label')
  });
}
